spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: provide your id
            client-secret: provide your client-secret
            scope:
              - profile
              - email
            redirect-uri:
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: provide it
            token-uri: provide it
            user-info-uri: provide it


server:
  port: 8081